### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Model/epoch0.pkl'

### ISSUE THREAD

**Issue by TTGodwwdw** [ecstayalive/Sparrow#1]
FileNotFoundError: [Errno 2] No such file or directory: 'Model/epoch0.pkl'
请问大佬，运行报错上面这个，是什么原因呀

**Comment by ecstayalive** [comment]
这个是一个Bug，因为在训练完成后，代码会将模型保存至 Model/ 文件夹下，可是在代码库中并没有这个文件夹，所以需要创建一个名字为 Model/ 的文件夹就可以解决报错。
同时Sparrow目前正在进行大量的更新，之后该项目将会依赖capsule_nn代码库，这是一个包含动态路由的一个与pytorch规范兼容的代码库。由于Sparrow我大三的一个项目，许多代码并不robust，希望原谅。

**Comment by py990318** [comment]
有详细的论文做介绍吗，有的话可以提供一个链接吗

**Comment by ecstayalive** [comment]
> 有详细的论文做介绍吗，有的话可以提供一个链接吗

目前是没有的，因为这只是胶囊神经网络的一个简单应用，没有创新性。不过可以去看Hinton的胶囊神经网络的论文

**Comment by ecstayalive** [comment]
该问题在最新版本中已经解决

**Comment by ecstayalive** [comment]
该问题在最新版本中已经解决
